app/urls.py
from app import views
from django.urls import path, include
from app import views

app_name = 'app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    path('<pk>/', views.SchoolDetailView.as_view(), name='detail'),
    path('create/', views.SchoolCreateView.as_view(), name='create'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('app/', include('app.urls', namespace='app'))
]

app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('basic_app:detail', kwargs={'pk':self.pk})
    
class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    
    

app/views.py
from django.shortcuts import render
from django.views.generic import (View, TemplateView, 
                                  ListView, DetailView,
                                  CreateView, UpdateView,
                                  DetailView)
from . import models


# Create your views here.


class IndexView(TemplateView):
    template_name = 'app/index.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['injection'] = 'Basic injection'
        return context

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'app/school_details.html'

class SchoolCreateView(CreateView):
    fields = ('name', 'principal','location')
    model = models.School

app/templates/app/app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'app:list' %}">Schools</a></li>
            <li><a href="{% url 'admin:index' %}">Admin</a></li>
            <li><a href=""></a></li>
        </ul>

    </nav>
    {%block content %}
    {% endblock %}
</body>
</html>

app/templates/app/school_details.html
{% extends "app/app_base.html" %}

{% block content %}

<h1>Welcome to the schools details page!</h1>
<ol>
        <h2>School details:</h2>
        <p>Name: {{ school_detail.name}}</p>
        <p>Principal: {{ school_detail.principal}}</p>
        <p>Location: {{ school_detail.location}}</p>
        <h3>Students</h3>
        {% for student in school_detail.students.all %}
            <p>
                {{student.name}} is {{student.age}} years old
            </p>
        {% endfor %}
</ol>

{% endblock %}

app/templates/app/school_form.html
{% extends "app/app_base.html"%}

{% block content %}

<h1>
    {% if not form.instance.pk  %}
    Create School
    {% else %}
    Update School
    {% endif %}
</h1>

<form method="POST">
    {% form.as_p %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

{% endblock %}

app/templates/app/school_list.html
{% extends "app/app_base.html"%}

{% block content %}

<h1>Welcome to a list of all the schools!</h1>
<ol>
    {% for school in schools%}
        <h2>
            <li><a href="{{school.id}}">{{school.name}}</a></li>
        </h2>
    {% endfor %}
</ol>

{% endblock %}

templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'app:list' %}">Schools</a></li>
            <li><a href="{% url 'admin:index' %}">Admin</a></li>
            <li><a href=""></a></li>
        </ul>

    </nav>
    {%block content %}
    {% endblock %}
</body>
</html>

templates/app/index.html
{% extends "app/base.html"%}

{% block content %}
    <div>
        <h1>Home Page</h1>
    </div>
{% endblock %}